print("This text")
print("This number", 5, 9)
print("This number", 5, 9, sep=" Potato ")
print("This number", 5, 9, sep=" Potato ", end=". \n\n")
print("This number", 5, 9, sep=" Potato ", end=". ")
print("This number", 5, 9, sep=" Potato ", end=". ")
